public class Operations {
    
    public Integer sum(integer a, integer b){
        integer c=(a+b);
        return c;
    }
      public Integer sub(integer a, integer b){
        integer c=(a-b);
        return c;
    }
      public Integer mul(integer a, integer b){
        integer c=(a*b);
        return c;
    }
      public Integer div(integer a, integer b){
        integer c=(a/b);
        return c;
    }

}